# Generated by Django 2.2 on 2019-04-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter this cat's name", max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(blank=True, max_length=20, null=True)),
                ('father', models.CharField(blank=True, max_length=10, null=True)),
                ('mother', models.CharField(blank=True, max_length=10, null=True)),
                ('mate', models.CharField(blank=True, max_length=10, null=True)),
                ('health', models.CharField(blank=True, choices=[('c', 'Cough'), ('p', 'Pregnant'), ('h', 'Hungry'), ('t', 'thirsty')], default='h', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('effect', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Explore with a lovely name', max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('money', models.IntegerField(default=200)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='Park')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Park')),
            ],
            options={
                'ordering': ['park'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Food')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Master')),
            ],
            options={
                'ordering': ['master'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Site')),
            ],
            options={
                'ordering': ['site', 'cat'],
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Food')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Market')),
            ],
            options={
                'ordering': ['price', '-num'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Food')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Market')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Master')),
            ],
            options={
                'ordering': ['-num', 'master'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimacy', models.IntegerField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Master')),
            ],
            options={
                'ordering': ['master', 'cat'],
            },
        ),
        migrations.CreateModel(
            name='Enjoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Food')),
            ],
            options={
                'ordering': ['cat'],
            },
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(blank=True, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Master')),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Park')),
            ],
            options={
                'ordering': ['master', 'cat'],
            },
        ),
    ]
