# Generated by Django 2.2 on 2019-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.RemoveField(
            model_name='market',
            name='id',
        ),
        migrations.RemoveField(
            model_name='master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='park',
            name='id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='cat',
            name='health',
            field=models.CharField(blank=True, choices=[('c', 'Cough'), ('p', 'Pregnant'), ('h', 'Hungry'), ('t', 'thirsty')], default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(help_text="Enter this cat's name", max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(help_text='Explore with a lovely name', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
