# Generated by Django 2.2 on 2019-04-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='intimacy',
        ),
        migrations.AlterField(
            model_name='master',
            name='money',
            field=models.IntegerField(default=200),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimacy', models.IntegerField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Cat')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Master')),
            ],
            options={
                'ordering': ['master', 'cat'],
            },
        ),
    ]
