# Generated by Django 2.2 on 2019-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='intimacy',
            field=models.IntegerField(default=50),
        ),
    ]
