# Generated by Django 2.2 on 2019-04-06 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='mather',
            new_name='father',
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('e6700626-5ec6-4f31-ab64-9ea9e867c28a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('bbc310ea-d683-4114-879f-c3782cb76bfe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.UUIDField(default=uuid.UUID('0e302e41-ddac-4d54-8260-3c20bcd18e4a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f1775b1e-1f17-4130-90aa-f0827d7e0701'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_id',
            field=models.UUIDField(default=uuid.UUID('dd2b8b29-c206-47fb-b712-557f6889e5f4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.UUIDField(default=uuid.UUID('b94d2fd9-df3a-477d-bf05-372fa83a92a8'), primary_key=True, serialize=False),
        ),
    ]
