# Generated by Django 2.2 on 2019-04-06 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190407_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('86f63caf-2a5b-4f7c-869c-f8462ab297b6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('ceaf1f80-26f9-412a-b6f7-773fb5dcc695'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.UUIDField(default=uuid.UUID('e446c79a-2b5c-41bf-a963-ac183e87294d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0d86b317-3066-4d92-807d-b1d432e35b3e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_id',
            field=models.UUIDField(default=uuid.UUID('821a6b30-10d9-4541-a411-ec35b98f270b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.UUIDField(default=uuid.UUID('c57a0d81-b556-41eb-a1f8-bdf23d3b5f3a'), primary_key=True, serialize=False),
        ),
    ]
