# Generated by Django 2.2 on 2019-04-06 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190407_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.UUIDField(default=uuid.UUID('9b988bc0-9aba-4ce6-80dd-64cc9a47f4bb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='father',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mother',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='effect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.UUIDField(default=uuid.UUID('ad7fa608-038a-46c1-b9dc-e139c3c02eac'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.UUIDField(default=uuid.UUID('92e07017-fa65-4655-9551-b41a2f002280'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('e5ae0d0e-0713-4a47-af7a-5cf2404bb485'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_id',
            field=models.UUIDField(default=uuid.UUID('40119d91-d80a-46df-ac9b-6db74a77b2fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.UUIDField(default=uuid.UUID('f91b0399-c2e6-46e5-b68e-6ba6ff81a9cf'), primary_key=True, serialize=False),
        ),
    ]
